before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X github.com/organicveggie/psychic-tribble/build.Version={{.Version}}
      - -X github.com/organicveggie/psychic-tribble/build.Commit={{.Commit}}
      - -X github.com/organicveggie/psychic-tribble/build.Date={{.Date}}
      - -X github.com/organicveggie/psychic-tribble/build.BuiltBy=goreleaser
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
